index.css
index.html
snek.js

- Resolves: https://github.com/Pamblam/snek/issues/4

[UI] Making it look nicer

---

index.css

Changed the colours to slightly brighter

Made changes to the background colour

---

classes.js
snek.js

Added a width property to snek which is used to set the Context's line width and food dimensions. Added optional "tolerance" argument to isPointTouchingLine to account for snek's bigger size. 
Fixes #1

[UI] Make snek and food bigger

---

index.html
snek.js

Added select for changing canvas size

---

.gitignore
classes.js
nbproject/private/private.properties
nbproject/project.properties
nbproject/project.xml
snek.js

Fixed the bug that was causing the ass-end of snek's tail to grow for no reason.

Fix long tail issue

---

snek.js

Tomato emoji as food, it though looks like a dot, just to maintain its size at width of the line.

added tomato emoji as food

---

.gitignore
index.css
index.html
snek.js

Add scoreboard

---

index.css
snek.js

Check user screen size and only allow options smaller than the screen.
Make sure canvas is always centered no matter what size is chosen.
I think scrolling was disabled. Please re-enable it so scores can be seen.

FIX Canvas sizes #13

---

README.md
index.css
snek.js

Also enabled scrolling, as bigger resolutions cause the high score list to go down.

Don't list sizes bigger than the window size

---

README.md

Added Mobeen Abdullah as contributors list in README.md

Added Mobeen Abdullah as contributors list

---

index.css
snek.js

Added a hidden class and the appearance and disappearance of the resolutions button if the game starts and stops.

Resolutions removed when game starts (Issue #27)

---

index.html

Fixes the linebreak between input and button.

---

README.md
classes.js
index.css
snek.js

Reference: [Issue #14 ](https://github.com/Pamblam/snek/issues/14)
**Snake Color**
I added a color property to snake in the "classes.js" file. The property default value is "green". Actually, the color is changed in the "snek.js" file: In the "draw()" function, i added the following line of code: `ctx.strokeStyle = snek.color`.
**Tomato Color**
In the same file, I added the following line of code to change the color of tomato: 
`let tomatoColor = "tomato"`
`ctx.fillStyle = tomatoColor`
**Canvas background and border**
To change canvas background and border colors, I modified the css file "index.css". 
`canvas { background: "lightgreen"; border: 1px solid "darkgreen" };`
<a href="https://imgur.com/GPD8zMf"><img src="https://i.imgur.com/GPD8zMf.gif" title="source: imgur.com" /></a>

Colors of snake, tomato and canvas changed! 

---

index.html

Fixed the Play button.  It should no longer be displayed with the unwanted spacing.  I thought the border was a little odd once it was inline, so I updated the colors a bit too.

BugFix: Play Button

---

README.md
index.html
snek.js

Had problems with arrow keys = scrolling, added functionality to hide/show the highscore. This improves it a lot!

Toggle Scores

---

README.md
snek.js

Added preventDefault if the focus is not in the input.

#47 Spacebar makes the page jump 

---

README.md
index.css
index.html

Rank styles

---

snek.js

#44 Default canvas size not listed in canvas sizing options.

---

index.css

Fixed the hard corners that were on the timer and separated the elements so they were no longer touching.

Fixed spacing between elements and corners

---

scripts/game.js

Add atlasRand to Contributors List

---

README.md
scripts/game.js

Closes #75 
The screen which asks for the player's username will always be shown, with the field being pre-populated if the username is stored in localstorage.

Always show options screen

---

README.md
scripts/game.js

- updated food logic (https://github.com/Pamblam/snek/commit/7871f778d95d82cd2b07d64d7666dfa588754bf6#diff-5e7f061e1ef9278a78ba2d81da1e38eeR113)
- standardized variables to snakecase
Fixes #87

Added logic to display 🍅 70% of the time

---

index.html
scripts/game.js
styles/index.css

For issue #80 
- Added radio buttons for playerMode(single/multi), playerColor(red/yellow/blue/brown), and gameMode(stamina/longest_win)
- Updated game.js to work with the new form
- adjusted styles.css

Added player form with options for playerMode, playerColor, and gameMode

---

index.html

#92 I really hope I am not misunderstanding again. I feel that I have caused enough extra work for you. crossing fingers.
Ideally the sizing field is now moved to the main page.
After trying a couple of times it does work in the playing mode.

add size to main page on multiplayer-branch
